# Generated by Django 2.1.5 on 2019-01-06 01:54

import autoslug.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=70)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
                ('weight', models.IntegerField()),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('menu_title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
                ('published', models.BooleanField()),
                ('navbar', models.BooleanField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
            ],
        ),
    ]
