# Generated by Django 2.1.5 on 2019-01-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20190108_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='adidas', max_length=200),
            preserve_default=False,
        ),
    ]
