# Generated by Django 2.1.5 on 2019-01-09 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default= None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category'),
            preserve_default=False,
        ),
    ]
